# Register
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "email": "omrigo3145@gmail.com",
    "password": "om3fds12"
}
###

# Login
POST http://localhost:3001/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "omrigo312@gmail.com",
    "password": "omrigo312"
}
###

# Get all vacations
GET http://localhost:3001/api/vacations HTTP/1.1
###

# Create a vacation
POST http://localhost:3001/api/vacations HTTP/1.1
content-type: application/json

{
    "description": "Enjoy the true city life of New York City",
    "destination":"New York, USA",
    "imageUrl": "https://media.architecturaldigest.com/photos/5da74823d599ec0008227ea8/16:9/w_2560%2Cc_limit/GettyImages-946087016.jpg",
    "price": "299",
    "startDate": "2021-03-04",
    "endDate": "2021-03-09"
}
###

# Modify a vacation
PUT http://localhost:3001/api/vacations/9 HTTP/1.1
content-type: application/json

{
    "description": "Enjoy the true city life of New York City",
    "destination": "New York, USA",
    "imageUrl": "https://media.architecturaldigest.com/photos/5da74823d599ec0008227ea8/16:9/w_2560%2Cc_limit/GettyImages-946087016.jpg",
    "price": "399",
    "startDate": "2021-03-04",
    "endDate": "2021-03-09",
    "followers": 0
}
###

# Delete a vacation
DELETE http://localhost:3001/api/vacations/10 HTTP/1.1
###